name: alarm
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.8+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_bloc: ^8.1.2
  equatable: ^2.0.3
  intl: ^0.17.0
  lottie: ^2.2.0
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^12.0.4
  shared_preferences: ^2.0.13
  package_info_plus: ^4.0.1
  path_provider: ^2.0.9
  open_filex: ^4.3.2
  permission_handler: ^10.0.0
  firebase_messaging: ^14.2.5
  firebase_core: ^2.7.0
  flutter_svg: ^2.0.2
  expandable: ^5.0.1
  audioplayers: ^3.0.1
  flutter_native_splash: ^2.2.4
  byte_converter: ^1.3.0
  flutter_osm_plugin: ^0.42.0
  html: ^0.15.0
  geolocator: ^9.0.1
  flutter_background_service: ^2.3.8
  geocoding: ^2.0.5
  lazy_load_scrollview: ^1.3.0
  flutter_html: ^3.0.0-alpha.3
  csv: ^5.0.1
  flutter_sticky_header: ^0.6.4
  fl_animated_linechart: ^1.1.6
  animated_text_kit: ^4.2.2
  page_transition: ^2.0.9
  app_settings: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter_native_splash:
    image: assets/images/splash_icon.png
    color: "252629"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/song/cancel/
    - assets/song/alarm/
    - assets/images/
    - assets/icons/

     

  fonts:
    - family: Days
      fonts:
        - asset: fonts/days.ttf
    - family: 8Bit
      fonts:
        - asset: fonts/8bit.ttf

        

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
